spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    password: dbuser
    username: dbuser
  jpa:
    properties:
      format_sql: true
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /iplstats
